/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Config Manifest schema
 */
export interface ConfigManifestSchema {
	version: string;
	title: string;
	properties: ConfigManifestKeys[];
}
export interface ConfigManifestKeys {
	[k: string]: ConfigManifestItem;
}
/**
 * This interface was referenced by `ConfigManifestKeys`'s JSON-Schema definition
 * via the `patternProperty` "^[A-Za-z0-9_-]+$".
 */
export interface ConfigManifestItem {
	type:
		| 'string'
		| 'string?'
		| 'number'
		| 'number?'
		| 'integer'
		| 'integer?'
		| 'boolean'
		| 'boolean?';
	description?: string;
	maxLength?: number;
	minLength?: number;
	pattern?: string;
	placeholder?: string;
}
