FROM node:latest

WORKDIR /usr/src/app
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.16.0/bin/linux/amd64/kubectl && \
	chmod +x ./kubectl && \
	mv ./kubectl /usr/local/bin/kubectl

COPY package* ./

RUN npm i

COPY . .

CMD [ "bash", "-c", "--", "while true; do sleep 1; done" ]
