FROM node:alpine

RUN apk update && apk add curl

WORKDIR /usr/src/app
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.16.0/bin/linux/amd64/kubectl && \
	chmod +x ./kubectl && \
	mv ./kubectl /usr/local/bin/kubectl

COPY package* ./

RUN npm ci

COPY . .

CMD [ "ash", "-c", "while true; do sleep 1; done" ]
